# Discord Bot Configuration
discord:
  bot-token: "YOUR_BOT_TOKEN_HERE"
  # Optional: Your Discord Server/Guild ID. If set, slash commands are registered to this guild instantly.
  # If left empty, commands are registered globally (can take up to an hour to appear).
  # If you provide a Guild ID, ensure it is correct and your bot is a member of that guild.
  # An invalid or inaccessible Guild ID (like "1370985075235356722" if that was the ID you were trying to use)
  # will cause warnings (e.g., "Could not find Discord guild with ID") and prevent guild-specific features from working correctly.
  guild-id: ""

# Synchronization Settings
sync:
  # Interval in minutes for periodic role synchronization. Set to 0 to disable.
  interval-minutes: 5

# Linking Process Settings
linking:
  # How long in minutes a link request from Discord to Minecraft remains valid.
  request-timeout-minutes: 5
  # Set Discord nickname to Minecraft username upon linking, and remove it on unlinking.
  # The bot needs the "Manage Nicknames" permission in Discord for this to work.
  synchronize-discord-nickname: true

# Role Synchronization Rules
roles:
  # Role Mappings: Define which in-game groups correspond to which Discord roles, and their sync direction.
  # Each mapping is an object with:
  #   ingame: "ingame_group_name"
  #   discord: "discord_role_id"
  #   direction: "BOTH" | "INGAME_TO_DISCORD" | "DISCORD_TO_INGAME" (Default: "BOTH" if omitted)
  #
  # Example:
  # - ingame: "admin"
  #   discord: "123456789012345678"
  #   direction: "BOTH"
  # - ingame: "moderator"
  #   discord: "098765432109876543"
  #   direction: "INGAME_TO_DISCORD"
  # - ingame: "vip"
  #   discord: "112233445566778899" # Will default to "BOTH" if direction is missing
  mappings: []

# Messages - Customize messages sent to players. Use '&' for color codes.
# Placeholders:
# %discord_user_displayname% - Discord user's display name (global name if available, otherwise username)
# %discord_user_tag% - Discord user's tag (e.g., Username#1234 or just Username if new system)
# %mc_username% - Minecraft player's username
# %your_mc_username% - The Minecraft username of the player receiving the message (used in contexts where they need to provide it)
messages:
  link:
    request_received_ingame: "&aRequest received to link to the Discord account \"&e%discord_user_displayname%&a\" (&e%discord_user_tag%&a). Type &e/link&a or click &e[HERE]&a to link accounts."
    request_sent_discord: "Link request sent to Minecraft player &e%mc_username%&r. They need to type &e/link&r in-game to confirm."
    no_pending_request_ingame: "&cYou have no pending link requests. Ask a Discord user to use /link %your_mc_username% in the Discord server."
    already_linked_ingame: "&cYour Minecraft account is already linked to a Discord account."
    already_linked_discord_self: "&cYour Discord account is already linked to a Minecraft account."
    already_linked_discord_other_mc: "&cThe Minecraft account &e%mc_username%&c is already linked to another Discord account."
    already_linked_discord_other_discord: "&cYour Discord account is already linked to the Minecraft account &e%mc_username%&c."
    success_ingame: "&aYour Minecraft account has been successfully linked with Discord account &e%discord_user_tag%&a!"
    success_discord: "&aYour Discord account has been successfully linked with Minecraft account &e%mc_username%&a!"
    player_not_online_discord: "&cPlayer &e%mc_username%&c is not currently online."
    error_discord: "&cAn error occurred while trying to send a link request. Please try again later."
    request_expired_ingame: "&cYour pending link request has expired. Please ask the Discord user to send a new one."
  unlink:
    not_linked_ingame: "&cYour Minecraft account is not linked to any Discord account."
    success_ingame: "&aYour Minecraft account has been successfully unlinked."
    error_ingame: "&cAn error occurred while trying to unlink your account."
    # Messages for Discord /unlink command
    not_linked_discord: "&cYour Discord account is not linked to any Minecraft account."
    success_discord: "&aYour Discord account has been successfully unlinked from the Minecraft account &e%mc_username%&a."
    error_discord: "&cAn error occurred while trying to unlink your account from Discord."
