# Discord Bot Configuration
discord:
  bot-token: "YOUR_BOT_TOKEN_HERE"
  # Optional: Your Discord Server/Guild ID. If set, slash commands are registered to this guild instantly.
  # If left empty, commands are registered globally (can take up to an hour to appear).
  # If you provide a Guild ID, ensure it is correct and your bot is a member of that guild.
  # An invalid or inaccessible Guild ID (like "1370985075235356722" if that was the ID you were trying to use)
  # will cause warnings (e.g., "Could not find Discord guild with ID") and prevent guild-specific features from working correctly.
  guild-id: ""
  # The invite link for your Discord server. Leave empty if you don't want to show one.
  invite-link: "https://discord.gg/yourinvitecode"

# Synchronization Settings
sync:
  # Interval in minutes for periodic role synchronization. Set to 0 to disable.
  interval-minutes: 5

# Linking Process Settings
linking:
  # How long in minutes a link request from Discord to Minecraft remains valid.
  request-timeout-minutes: 5
  # Set Discord nickname to Minecraft username upon linking, and remove it on unlinking.
  # The bot needs the "Manage Nicknames" permission in Discord for this to work.
  synchronize-discord-nickname: true

# Role Synchronization Rules
roles:
  # Role Mappings: Define which in-game groups correspond to which Discord roles, and their sync direction.
  # Each mapping is an object with:
  #   ingame: "ingame_group_name"
  #   discord: "discord_role_id"
  #   direction: "BOTH" | "INGAME_TO_DISCORD" | "DISCORD_TO_INGAME" (Default: "BOTH" if omitted)
  #
  # Example:
  # - ingame: "admin"
  #   discord: "123456789012345678"
  #   direction: "BOTH"
  # - ingame: "moderator"
  #   discord: "098765432109876543"
  #   direction: "INGAME_TO_DISCORD"
  # - ingame: "vip"
  #   discord: "112233445566778899" # Will default to "BOTH" if direction is missing
  mappings: []

# Message strings are now managed in messages.yml
# This allows for easier updates to default messages if you haven't customized them.
# You can find messages.yml in your plugins/DiscordRoleSync/ folder.
