name: DiscordRoleSync
version: '1.0-SNAPSHOT'
main: net.gabbage.discordRoleSync.DiscordRoleSync
api-version: '1.21'
authors: [ Ginotuch ]
description: Syncs in-game roles to Discord roles
website: gabbage.net
commands:
  link:
    description: Links your Minecraft account to your Discord account or accepts a pending link request.
    usage: "/link"
  unlink:
    description: Unlinks your Minecraft account from your Discord account.
    usage: "/unlink"
  drsreload:
    description: Reloads the DiscordRoleSync plugin and its configuration.
    usage: "/drsreload"
    permission: discordrolesync.reload
  denylink:
    description: Denies a pending link request from Discord.
    usage: "/denylink"
    permission: discordrolesync.denylink
  discord:
    description: Shows Discord link status and invite link.
    usage: "/discord"
    permission: discordrolesync.discord
permissions:
  discordrolesync.link:
    description: Allows users to use the /link command.
    default: true
  discordrolesync.unlink:
    description: Allows users to use the /unlink command.
    default: true
  discordrolesync.denylink:
    description: Allows users to deny a pending link request.
    default: true
  discordrolesync.discord:
    description: Shows Discord link status and invite.
    default: true
  discordrolesync.reload:
    description: Allows users to reload the DiscordRoleSync plugin.
    default: op
